pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'terraform -v'
            }
        }
        // stage('Test') {
        //     steps {
        //         echo 'Testing..'
        //     }
        // }
        // stage('Deploy') {
        //     steps {
        //         echo 'Deploying....'
        //     }
        // }
    }
}