pipeline {
    agent any

    stages {
        stage('Git Checkout') {
            steps {
                git credentialsId: 
            }
        }
        stage('Terraform Init') {
            steps {
                sh 'terraform init'
            }
        }
        stage('terraform plan) {
            steps {
                sh 'terraform plan'
            }
        }
        stage('terraform apply') {
            steps {
                sh 'terraform apply --auto-approve'
            }
        }
    }
}